# Generated by Django 2.0 on 2020-04-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_permission_parent_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='parent_url',
        ),
        migrations.AddField(
            model_name='permission',
            name='parent_menu',
            field=models.ManyToManyField(blank=True, null=True, related_name='_permission_parent_menu_+', to='rbac.Permission', verbose_name='父导航标志'),
        ),
    ]
