# Generated by Django 2.0 on 2020-05-04 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20200429_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='parent_menu',
        ),
        migrations.AddField(
            model_name='permission',
            name='parent_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Permission', verbose_name='父菜单标志'),
        ),
    ]
