# Generated by Django 2.0 on 2020-05-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20200504_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=128, null=True, verbose_name='含正则的URL'),
        ),
    ]
