# Generated by Django 2.0 on 2020-05-04 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_auto_20200504_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='alias',
            field=models.CharField(max_length=32, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='parent_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Permission', verbose_name='父菜单标志'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='含正则的URL'),
        ),
    ]
